# Generated by Django 5.2.6 on 2025-10-24 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartDayApp', '0002_casa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasaMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('Usuarios', 'Usuário'), ('Responsavel', 'Responsável')], default='Usuarios', max_length=20)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_relacionados', to='SmartDayApp.casa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casas_relacionadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('casa', 'usuario')},
            },
        ),
    ]
