# Generated by Django 5.2.6 on 2025-10-24 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartDayApp', '0003_casamembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='casa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='SmartDayApp.casa'),
        ),
    ]
