# Generated by Django 5.2.6 on 2025-11-07 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartDayApp', '0006_gasto_rendamensal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='rendamensal',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='rendamensal',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='rendamensal',
            name='nota',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('renda', 'Entrada'), ('gasto', 'Saída')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='local',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
